//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpcomingMovies.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpcomingMovies.Resources.AllResources", typeof(AllResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/movie/upcoming?api_key=.
        /// </summary>
        public static string AllMoviesLinkTemplate {
            get {
                return ResourceManager.GetString("AllMoviesLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ?api_key=.
        /// </summary>
        public static string ApiKeyForLink {
            get {
                return ResourceManager.GetString("ApiKeyForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  days ago.
        /// </summary>
        public static string ForDaysLeft {
            get {
                return ResourceManager.GetString("ForDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.themoviedb.org/t/p/w600_and_h900_bestv2.
        /// </summary>
        public static string ForImageURL {
            get {
                return ResourceManager.GetString("ForImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відсутнє підключення до Інтернету. Перевірте підключення та перезапустіть програму.
        /// </summary>
        public static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.themoviedb.org/3/movie/.
        /// </summary>
        public static string MovieLinkTemplate {
            get {
                return ResourceManager.GetString("MovieLinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        public static string NoDaysLeft {
            get {
                return ResourceManager.GetString("NoDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.nannihealthfood.com/img/m/11.jpg.
        /// </summary>
        public static string NoImagePath {
            get {
                return ResourceManager.GetString("NoImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Більше сторінок немає.
        /// </summary>
        public static string NoMorePagesMessage {
            get {
                return ResourceManager.GetString("NoMorePagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;page=.
        /// </summary>
        public static string PageForLink {
            get {
                return ResourceManager.GetString("PageForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;region = UA.
        /// </summary>
        public static string RegionForLink {
            get {
                return ResourceManager.GetString("RegionForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;sort_by=popularity.
        /// </summary>
        public static string SortForLink {
            get {
                return ResourceManager.GetString("SortForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрити програму?.
        /// </summary>
        public static string WantToClose {
            get {
                return ResourceManager.GetString("WantToClose", resourceCulture);
            }
        }
    }
}
